-- Run this once in the Supabase SQL Editor (Dashboard → SQL Editor → New query)

-- 1. Scores table
create table if not exists public.scores (
  id            bigint generated by default as identity primary key,
  game_id       text not null,
  player_name   text not null default 'Anonymous',
  score         integer not null check (score >= 0),
  created_at    timestamptz not null default now()
);

-- 2. Fast top-N queries
create index if not exists scores_game_score_idx
  on public.scores (game_id, score desc, created_at desc);

-- 3. Row Level Security
alter table public.scores enable row level security;

-- Allow anyone to read scores
create policy "Public read scores"
  on public.scores
  for select
  using (true);

-- Allow anyone to insert a score (basic public leaderboard)
-- You can tighten this later with auth or rate limits
create policy "Public insert scores"
  on public.scores
  for insert
  with check (
    char_length(player_name) <= 20
    and score >= 0
    and score < 10000000
  );

-- Optional: prevent updates/deletes from the public anon key
-- (no update/delete policies = blocked by default when RLS is on)
